backend:
  name: github
  branch: main 
  repo: Smartidly-org/smarthostly-docs
  auth_scope: repo # Ensure repo scope is set for GitHub authentication
  base_url: https://smarthostly-docs.vercel.app # Use your Vercel deployed site URL
  auth_endpoint: api/auth # Auth endpoint for OAuth


# These lines should *not* be indented
media_folder: "static/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/" # The src attribute for uploaded media will begin with /images/uploads

collections:
- name: "docs"
  label: "Documentation"
  folder: "docs"
  create: true
  slug: "{{slug}}"
  fields:
    - { label: "Title", name: "title", widget: "string" }
    - { label: "Body", name: "body", widget: "markdown" }